config/routes.rb
Rails.application.routes.draw do
  get "/palette", to: "palette#index"

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/api/graphql"
  end
  post "/api/graphql", to: "graphql#execute"
  resources :articles, only: [:index, :edit, :new, :create, :update, :destroy]
  # root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history, :finders]

  has_one :legacy_article

  def archive
    update(archived_at: Time.now)
  end
end

app/models/article_transformer.rb
class ArticleTransformer
  def self.run(legacy_article_id)
    new(legacy_article_id).run
  end

  def initialize(legacy_article_id)
    @legacy_article_id = legacy_article_id
  end

  def run
    article = Article.create(article_attrs)
    legacy_article.update(transformed_at: Time.now, article_id: article.id)
    past_slugs.each do |slug|
      article.slugs.create(slug: slug)
    end
  end

  private

  def legacy_article
    @legacy_article ||= LegacyArticle.find(@legacy_article_id)
  end

  def article_data
    legacy_article.data
  end

  def article_attrs
    {
      created_at: updated_at,
      legacy_article_id: legacy_article.id,
      published_at: article_data.dig("published_at", "$date"),
      slug: current_slug,
      title: article_data["title"],
      updated_at: updated_at,
    }
  end

  def updated_at
    timestamp = article_data["updated_at"]

    return timestamp if timestamp.nil? || timestamp.is_a?(String)

    timestamp["$date"]
  end

  def current_slug
    article_data["slug"]
  end

  def past_slugs
    slugs = Array(article_data["slugs"])
    return slugs unless slugs.any?

    slugs - [current_slug]
  end
end

app/models/legacy_article.rb
class LegacyArticle < ApplicationRecord
  has_one :article

  def self.create_if_new(data)
    positron_id = data.dig("_id", "$oid")
    return if LegacyArticle.where(positron_id: positron_id).any?

    LegacyArticle.create(data: data, positron_id: positron_id)
  end

  def transformed?
    !transformed_at.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  expose(:article)
  expose(:articles) { Article.where(archived_at: nil).order(created_at: :desc).limit(20) }

  def create
    if article.save
      redirect_to edit_article_path(article)
    else
      render :new
    end
  end

  def update
    if article.update(article_params)
      redirect_to articles_path
    else
      render :edit
    end
  end

  def destroy
    article.archive
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title)
  end
end

app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  # If accessing from outside this domain, nullify the session
  # This allows for outside API access while preventing CSRF attacks,
  # but you'll have to authenticate your user separately
  # protect_from_forgery with: :null_session

  def execute
    variables = prepare_variables(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = NeutronSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue StandardError => e
    raise e unless Rails.env.development?
    handle_error_in_development(e)
  end

  private

  # Handle variables in form data, JSON body, or a blank value
  def prepare_variables(variables_param)
    case variables_param
    when String
      if variables_param.present?
        JSON.parse(variables_param) || {}
      else
        {}
      end
    when Hash
      variables_param
    when ActionController::Parameters
      variables_param.to_unsafe_hash # GraphQL-Ruby will validate name and type of incoming variables.
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{variables_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { errors: [{ message: e.message, backtrace: e.backtrace }], data: {} }, status: 500
  end
end

app/controllers/palette_controller.rb
class PaletteController < ApplicationController
end

app/helpers/application_helper.rb
class Palette
  def initialize(render_method)
    @render_method = render_method
  end

  # could define the components one at a time
  def Text(options, &block)
    component = TextComponent.new(**options)
    @render_method.call(component, &block)
  end

  # or could do meta programming
  def method_missing(method, options, &block)
    klass_name = "#{method}Component"
    component = klass_name.constantize.new(**options)
    @render_method.call(component, &block)
  end
end

module ApplicationHelper
  def r(klass_name, **options, &block)
    component = "#{klass_name}Component".constantize.new(**options)
    render(component, &block)
  end

  def p
    Palette.new(self.method(:render))
  end
end

app/views/articles/edit.html.haml
%h1 Article #{article.id}

= form_with model: article do |f|
  = f.text_field :title, autofocus: true
  = f.button "update"
  = f.button "archive", formmethod: :delete, data: { confirm: "Are you sure?" }

app/views/articles/index.html.haml
%h1 Recent Articles

%p= link_to "New Article", new_article_path

%ul
  - articles.each do |article|
    %li= link_to article.title, edit_article_path(article)

app/views/articles/new.html.haml
%h1 New Article

= form_with model: article do |f|
  = f.text_field :title, autofocus: true
  = f.button "create"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Neutron</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/palette/index.html.haml
= render TextComponent.new variant: "xxl" do
  Text XXL

= render TextComponent.new variant: "xl" do
  Text XL

= render TextComponent.new variant: "lg" do
  Text LG

= render TextComponent.new variant: "md" do
  Text MD

= render TextComponent.new variant: "sm" do
  Text SM

= render TextComponent.new variant: "xs" do
  Text XS

= r "Text", variant: "xxl" do
  Using a helper

= p.Text variant: "xxl" do
  Using a fancy helper

= p.Button variant: "primaryBlack" do
  Follow

= p.Button variant: "primaryBlack", disabled: true do
  Disabled Action